all: compilarCliente linkearCliente compilarServer linkearServer



compilarCliente:

	gcc -c client.c

compilarServer:

	gcc -c server.c

linkearCliente:

	gcc -o CLIENTE.exe client.o -pthread

linkearServer:

	gcc -o SERVIDOR.exe server.o -pthread



debug:

	gcc -g client.c -o cliente.dbg

	gcc -g server.c -o server.dbg -pthread

logCliente:

	gdb cliente.dbg core

logServer:

	gdb server.dbg core



limpiar:

	rm -f *.o *.exe *.dbg core